### PR TITLE
WIP: theano-like transform from dot -> gemm

### PR DESCRIPTION
**Pull request by jaberg**
Inspired by the fast turnaround on the last theano PR, I decided to push forward a little further:  this time I've made a graph that uses the "Dot" Op, which does not have a corresponding op in the ir. How would you deal with this?  Is the idea that for such cases, People With Good Judgement will decide whether to add an IR op?  Can IR Ops be added from outside the project as long as they are accompanied by code transformations that lower them?

I'd like to push this example as far as implementing an inplace update function with theano, that would use a BLAS gemm function to update a matrix.  This brings up how to transform the graph of add, mul, and dot into gemm, and how to work with preallocated data with PyKit (can PyKit generate modules with state?).

### CODE REVIEW

**Comment by markflorisson** [comment]
Thanks, I'll try to find some time the coming days. I think it depends on the use case:

```
1) if you need something a compiler needs to recognize and optimize, you need to extend the IR
2) if you can considere the operation as a runtime component (external or in pykit IR) -  or expressed as a series of existing opcodes, then that route should be preferred.
```

As for modules, yes, it supports global variables. So you'd have to use a global array variable. It's more likely you'll want to dynamically allocate it though, and rely on stack allocation if appropriate (small arrays).

The transformation to gemm would be fairly straightforward, a bigger problem is deciding the tradeoff between fusion and BLAS calls.

**Comment by markflorisson** [comment]
If you want a look at some sample transforms, have a look at pykit/ir/value.py, which defines the in-memory IR data structures. pykit/ir/traversal.py implements a simple visitor/transformer. You can also just loop over the operations in the blocks and use the replace method. There is an example transformer for PyObject <-> native value coercions in pykit/cpy/convert.py (although I think it should be rewritten in just plain C).

**Comment by jaberg** [comment]
I agree that in this case, some addition to the IR is appropriate, how about extending it with BLAS calls? (How do you suggest dealing with types?) My rationale is that (a) lots of NumPy, SciPy, SymPy, and Theano expressions map pretty directly onto BLAS calls, and (b) there are lots of existing libraries that provide implementations of BLAS calls that our compiler backends might want to draw on. The BLAS interface has been a stable matrix-based instruction set since the 70s, so I think it makes perfect sense to have BLAS functions in the IR. (FWIW, I suspect the same case could be made for LAPACK, but I think it can be discussed separately.)

So, about those types. From the look of how you translated the 'add' and 'mul' expressions before, it looks like the type should be left out of the IR Op.  By analogy, the BLAS Ops could be e.g.
- gemm
- syrk
- ger
- gemv
- dot

How would you represent the fact that the library calls in question are not pure, but they do, in effect have an output, that overwrites one of the inputs?

With regards to whether a backend should call a library or just emit scalar code that can be fused with surrounding stuff, that decision requires an estimate of the size and physical layout of the arrays involved. How were you thinking of tracking that sort of information?

@mrocklin - this would implicate something like your computations project, how is this sounding to you?

**Comment by mrocklin** [comment]
> How would you represent the fact that the library calls in question are not pure, but they do, in effect have an output, that overwrites one of the inputs?

One way is to make `puregemm`, `puresyrk`, `puregesv`, ... operations that include a copy.  Later, if the IR supports inplace operations then these be expanded to the impure subroutine (e.g. `gemm`) and a copy.  Other graph transformations can then strip away unnecessary copies.  That's how I handle this issue at least.

I like the idea of supporting BLAS/LAPACK for the reasons you mentioned.  I'm not sure at what level actual routines should be included.  I can envision both high and low level IRs where these routines are inappropriate.

I think that the ideal design would support future inclusion of such operations.  I don't think they should be part of the fundamentals.

**Comment by markflorisson** [comment]
Hey James, Matthew,

I think what we want is a fully typed IR, with types for every operation producing a result. So for a dot operation the type is the result array type. For "void" operations such as control flow etc there is the Void type. Does that make sense?

What the compiler needs to know is what an operation is doing, then analyze and optimize, and then you want to map to BLAS. For instance, if the result isn't used, there's no point in performing the operation, or if it can be fused with a later expression, then you could have mapped to perhaps a better sequence of BLAS calls.

Now, pykit doesn't care what an external function does. It can overwrite an array if it wants to. If you provide no hints, then pykit assumes nothing, i.e. it assumes side-effects and it assumes anything may have been written to or read from the arrays - unless you tell it otherwise, I imagine through metadata.

Matthew describes some good transformation steps, I think what we'll end up with is a pykit-blas, pykit-cpython, etc, that each provide transformations (and perhaps runtime code) that specialize in some way.

As for array types, right know there are typedefs in place, e.g. 'typedef Array<double, 2> my_special_type', for which code can maintain a map: `{ my_special_type : metadata(shape=[10, 10]) }`. An problem with that is that if some other transformation pass derives new types from those types the mapping will be out of date, maybe we need each type to have metadata itself which is preserved by passes? Or maybe we can start with the simplest thing and incorporate all these things and make them optional.

**Comment by markflorisson** [comment]
Thanks, merged in master.

**Pull request closed without merging**
